#!/bin/bash

function main() {
    check_version

    log_color "Every control are checked" "green"
}

function check_version(){
    last_tag=$(git tag | tail -n 1)
    if [ -z ${last_tag} ];then
        return 0
    fi
    last_version=$(echo "${last_tag}" | grep -oP "\K[0-9].[0-9].[0-9]")

    file_version="./main.ps1"

    regex="\K([0-9].[0-9].[0-9])"
    current_version=$(grep -Po "${regex}" "${file_version}")

    vercomp ${current_version} ${last_version}
    result=$?
    case ${result} in
        0) op='=';;
        1) op='>';;
        2) op='<';;
    esac
    if [ ${op} == "=" ] || [ ${op} == "<" ];then 
        log "$(log_color "Careful your version is downgraded current:" "yellow") $(log_color "${current_version}" "red") $(log_color "last:" "yellow") $(log_color "${last_version}" "red")"
    fi
}

################################################################### Utils functions ###################################################################

###
# Compare version semver
# $1: [string], semver version compared (ex: 1.0.0)
# $2: [string], semver version to compare (ex: 1.1.1)
# returns: 0 if equal, 1 if $1 < $2, 2 if $1 > $2
###
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if ((10#${ver1[i]:=0} > 10#${ver2[i]:=0}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

function get_datetime {
    log $(date '+%Y-%m-%d %H:%M:%S')
}

function log {
    echo -e $@
}

function log_color {
    message=$1
    color=$2
    log ${COLORS[$color]}$message${COLORS[nc]}
}

typeset -A COLORS=(
    [default]='\033[0;39m'
    [black]='\033[0;30m'
    [red]='\033[0;31m'
    [green]='\033[0;32m'
    [yellow]='\033[0;33m'
    [blue]='\033[0;34m'
    [magenta]='\033[0;35m'
    [cyan]='\033[0;36m'
    [light_gray]='\033[0;37m'
    [light_grey]='\033[0;37m'
    [dark_gray]='\033[0;90m'
    [dark_grey]='\033[0;90m'
    [light_red]='\033[0;91m'
    [light_green]='\033[0;92m'
    [light_yellow]='\033[0;93m'
    [light_blue]='\033[0;94m'
    [light_magenta]='\033[0;95m'
    [light_cyan]='\033[0;96m'
    [nc]='\033[0m' # No Color
)

function log_verbose {
    message=$@
    date=$(get_datetime)
    if [ "${DEBUG}" = "true" ]; then log_color "[$date] $message" "light_blue"; fi
    return
}

main "$@"